services:
  devcontainer:
    container_name: devcontainer
    image: mcr.microsoft.com/devcontainers/javascript-node:1-22-bookworm
    volumes:
      - ../../..:/workspaces:cached
    network_mode: service:database
    command: sleep infinity
